version: '3.5'
services:
  db:
    image: mongo:latest
    container_name: db
    networks:
      - uad_network
  backend:
    container_name: backend
    image: jannisdev/uad:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - uad_network

networks:
  uad_network:
    name: uad_network

